### ISSUE TITLE
Incorrect casting within modules/reports/income_forecast.php

### ISSUE THREAD

**Issue by jwieder** [WHMCS/developer-docs#1]
Wasn't sure where else to provide this. Running the income forecast report in WHMCS 6.3.1 via
admin/reports.php?report=income_forecast produces a string of "mktime() expects parameter 6 to be long, string given in [...]" errors.

I identified the issue as an incorrect cast on line 40 of modules/reports/income_forecast.php. Replacing the original line:
    `$new_time = mktime(0,0,0,$month+$i,1,$year);`
With this revision:
    `$new_time = mktime(0,0,0,$month+$i,1,(int) $year);`
Resolves the error. Cheers.

**Comment by mattpugh** [comment]
Thank you for the report. In future please submit issues such as this via our bug reporting page @ www.whmcs.com/members/bugreport.php
