### ISSUE TITLE
UpgradeProduct Issue - Method getAvailableBillingCycles does not exist.

### ISSUE THREAD

**Issue by hamzarauf** [WHMCS/developer-docs#104]
UpgradeProduct API result shows - Method getAvailableBillingCycles does not exist.

**Comment by WHMCSPeter** [comment]
Hi @hamzarauf,

This GitHub Issue Tracker is for reporting issues with the Documentation specifically. For bugs within the product, please do report these via our dedicated Bug Report form here: https://bugs.whmcs.com/

Thanks!
