### ISSUE TITLE
IDE Helper, please

### ISSUE THREAD

**Issue by sburina** [WHMCS/developer-docs#106]
Hi!

Would it be possible for you to publish some kind of IDE helper file to help the developers?
I'm thinking something like [this one](https://gist.github.com/barryvdh/5227822), perhaps?

Thanks in advance!

**Comment by mewejo** [comment]
@sburina We're in the process of building a framework for WHMCS which should solve your problems for IDE hinting. We're happy to add features, classes and methods on request or accept PR's.

It recently received an update to make configurable options easier to deal with: https://github.com/grizzlyware/salmon-whmcs

**Comment by gac3k** [comment]
I've created something simple (for now) for a basic purposes, reflection based. For anybody interested
https://github.com/indicio-software/whmcs-ide-helper

I am going to extend it further :)

**Comment by WHMCSPeter** [comment]
Hi there,

My apologies in the delay in responding accordingly to this Issue.

At current, an IDE helper is not something that is intended to be provided via the Developer Documentation and for this reason, I will be closing this request.

I do however recommend checking out our Class Documentation at https://classdocs.whmcs.com/ which provides information on the publicly available classes and its respective methods. This documentation is updated on every feature release and sooner if other classes become available for use within that time.

Thanks for your comments.
