### ISSUE TITLE
Hook ClientEdit doesn't trigger

### ISSUE THREAD

**Issue by vipera7** [WHMCS/developer-docs#110]
I'm trying to trigger a custom function when a user edit his email.The code works well when I edit manualy in the admin page but on the customer page the hook isn't triggered.

my hook code (includes/hook/index.php): 

```
<?php
if ( !defined('WHMCS')) {
    header("Location: ../../index.php");
}

add_hook('ClientEdit', 1, function ($vars)
{
	file_put_contents('testLog.txt', 'TEST'.PHP_EOL , FILE_APPEND | LOCK_EX);
});
```

Admin page when edit:
![Admin](https://i.imgur.com/3kkrrJb.png)

Client page when edit:
![Client](https://i.imgur.com/pyKubHR.png)

**Comment by WHMCSMarcus** [comment]
Please kindly open a case with our Technical Support team so they may assist with this issue: https://www.whmcs.com/support/
