### ISSUE TITLE
Broken Link to Classes 

### ISSUE THREAD

**Issue by strausmann** [WHMCS/developer-docs#117]
On the Page https://developers.whmcs.com/domain-registrars/domain-information/ is the Link to the Classes wrong. 

Right URL is: https://docs.whmcs.com/classes/7.6/WHMCS/Domain/Registrar/Domain.html and not https://docs.whmcs.com/classes/7.6/WHMCS/Domain/Registrar/Domain_ns.html

**Comment by mattpugh** [comment]
Hi @strausmann, Thanks for bringing this to our attention. I can confirm this link has now been corrected.
