### ISSUE TITLE
UpdateInvoice lineItemId documentation missing

### ISSUE THREAD

**Issue by ZizzyZizzy** [WHMCS/developer-docs#118]
The documentation for UpdateInvoice doesn't specify exactly what 'lineItemId' means or how to obtain it.

In a logical world, line item 0 (or 1) would be the first line item in the invoice. That is not even close to the reality here. You must first call GetInvoice to obtain the "ID" from each line item you wish to update, which is absurd.

If the invoice only has one item, the 'lineItemId' you need can be found with **$whmcs_data['WHMCSAPI']['ITEMS']['ITEM']['ID']**:

```
            [ITEMS] => Array
                (
                    [ITEM] => Array
                        (
                            [ID] => 57593 # This is the lineItemId required for UpdateInvoice
                            [TYPE] => Addon
                            [RELID] => 4078  # This is the addon id
                            [DESCRIPTION] => Addon (13) - Full Backup and Restore - 1 Backup Max (2018-12-01 - 2018-12-31)
                            [AMOUNT] => 1.00
                            [TAXED] => 0
                        )

                )

```

If would have made much more sense to have an additional column in tblinvoiceitems with a lineItemId that starts with 0 (or 1) and increments for each line item. Instead, I have to make an additional API call before updating the invoice so I can grab some ridiculously obscure ID.

To add insult to injury, the API happily returns "success' if you supply ANY value for lineItemId, even if there is no such lineItemId in the database. It was a fantastic waste of over an hour pulling my hair out, trying to figure out why the invoice refused to update.

**Comment by mattpugh** [comment]
Hi @ZizzyZizzy,

Thanks for the feedback. I can certainly appreciate how having to know the line item ID may require additional API calls. It is however also the most reliable way to reference a given line item. 

I've opened case CORE-13014 internally to look at providing some clarification around `LineItemId` in the docs.
