### ISSUE TITLE
CreateInvoice shows status 'Unpaid'

### ISSUE THREAD

**Issue by ZizzyZizzy** [WHMCS/developer-docs#119]
Title explains it all. If you pass the autoapplycredit param to CreateInvoice and the customer has enough credit to pay the invoice fully, the API still returns "Unpaid" as the status of the invoice from the CreateInvoice call.

To get the true status of the invoice, you must use GetInvoice.

**Comment by whmcs-smueller** [comment]
Hi there,

Thanks for letting us know about this error.

I have opened an internal case to have this resolved. The case number for reference is CORE-18832.

I am going to close this case and we will endeavor to have the newly created case resolved and updated as quickly as possible.

Thanks again!
