### ISSUE TITLE
POST ERROR : You did not provide required custom field value for IsReseller

### ISSUE THREAD

**Issue by ItsNotMyFault** [WHMCS/developer-docs#123]
Trying to add a client through a post request from my C# app, when i get the response I get this error message : 
You did not provide required custom field value for IsReseller.

My problem : there is no mention of such custom field in the API.

Help me please

**Comment by JRawly** [comment]
Custom Fields are defined within WHMCS and can be unique per Client, Product, Addon and Support Department.
In this instance, the installation you are connecting to has a custom field on the action you are completing (you didn't advise which), which is required, and you will need to pass the custom field parameter listed in the documentation.

**Comment by JRawly** [comment]
The documentation for this command is correct, and does reference the customfield variable.
https://developers.whmcs.com/api-reference/addclient/

**Comment by ItsNotMyFault** [comment]
Oh ok, I see thanks, but how can I pass the specific custom field and his value? Just noticed I have 2 customField

**Comment by JRawly** [comment]
As stated on the documentation, you need to base64 and serialize the array.

You can see another example of how to do this on the Add Order API command - https://developers.whmcs.com/api-reference/addorder/

If you need further assistance, our support team will be happy to help!

https://www.whmcs.com/get-support

**Comment by ItsNotMyFault** [comment]
Just noticed my isResselet field is a checkbox how can I set it as check or uncheck?
![image](https://user-images.githubusercontent.com/46060080/52579936-420e9480-2df5-11e9-8c46-60d06a031a8e.png)

**Comment by ItsNotMyFault** [comment]
I can't findout how is presented a checkBox value with this this API. 
I tried as a boolean, as a string, a BIT. I don't have any clues on how to proceed aymore.
My other Custom field does work, but I kept getting this other error : IsReseller is required.

![capture](https://user-images.githubusercontent.com/46060080/52586578-dbde3d80-2e05-11e9-8b86-fb327130eccc.PNG)

Login Details Incorrect. Please try again.

**Comment by mutluakturk** [comment]
Hi everyone..
I have same problem. I'm trying to select custom fields with c# api but how it works i can't findout :'(

**Comment by arlindmusliu** [comment]
I had the same issue, for both an input field and checkbox. I followed this [example](https://laracasts.com/discuss/channels/laravel/how-to-insert-multiple-custom-fields-to-whmcs-api) and fixed the issue.

The response we get from WHMCS API is not the same format that we need to send for the update to work. The response is formatted as below (first one is an input field, second one is a checkbox):

[{
    "id" => "126",
    "value"  => "your content",
},
{
    "id" => "127",
    "value"  => "on",
}];

But, when we send the update request we need to do the following:

$customFields = [
    "126" => "your content",
    "127"  => "on",
];

$params = [
    'action' => 'AddClient',
	...$data,
    'customfields' => [base64_encode(serialize($customFields))]
];

For a selected checkbox you need to submit "on", and for unchecked submit "" as a response.
