### ISSUE TITLE
Can't add or edit CustomFields

### ISSUE THREAD

**Issue by ItsNotMyFault** [WHMCS/developer-docs#124]
I can edit or update  a client, but my custom field won't update! Help

![capture](https://user-images.githubusercontent.com/46060080/52590325-fff24c80-2e0e-11e9-9d43-35842c81d38e.PNG)

**Comment by JRawly** [comment]
Hi, 

This GitHub page is for issues occurring in the developer documentation - https://developers.whmcs.com .
If you have an issue with using the API, please contact WHMCS Support - https://www.whmcs.com/get-support
