### ISSUE TITLE
Notification Provider GitHub sample is dead

### ISSUE THREAD

**Issue by Heshmatkhah** [WHMCS/developer-docs#127]
The link to [GitHub repository](https://github.com/WHMCS/sample-notification-module) you provided in [the documentation](https://github.com/WHMCS/developer-docs/blob/6ddec49/notification-providers/getting-started.md) is dead and the repository no longer exists!!

![GitHub 404](https://user-images.githubusercontent.com/10222466/53916917-9c0f1c80-4078-11e9-8294-9623988620fd.PNG)

**Comment by WHMCSPeter** [comment]
Hi and sorry for the delay in response.

Thanks for the report. This was resolved.

Please don't hesitate to reach out to our Support team in future at https://www.whmcs.com/support
