### ISSUE TITLE
AddClient password field missing from documentation

### ISSUE THREAD

**Issue by vladmunteanu** [WHMCS/developer-docs#129]
The documentation shows AddClient calls with a `password` and `password2` field, but only `password2` is specified in the request parameters table.

Is `password` still available as a parameter? If so, I think it should be included in the parameters table.

https://developers.whmcs.com/api-reference/addclient/

**Comment by JRawly** [comment]
password is the legacy field used for admin authentication, not setting a client details. This is stated on the referenced https://developers.whmcs.com/api/authentication/ on the AddClient documention.

**Comment by vladmunteanu** [comment]
thanks @JRawly, sorry I have missed that.
