### ISSUE TITLE
Missing gateway modules callbacks page

### ISSUE THREAD

**Issue by KrisShannon** [WHMCS/developer-docs#13]
On the [3D Secure Process](https://developers.whmcs.com/payment-gateways/3d-secure/) page there is a link to a missing page:

"The return url should be a [callback file](https://developers.whmcs.com/gateway-modules/callbacks) to handle the response."

**Comment by KrisShannon** [comment]
It looks like this shoule be a link to [https://developers.whmcs.com/payment-gateways/callbacks/](https://developers.whmcs.com/payment-gateways/callbacks/)

**Comment by mattpugh** [comment]
Hi Kris, Thanks for letting us know about the broken link. We'll get it updated.
