### ISSUE TITLE
GetPayMethods - "API Function Not Found"

### ISSUE THREAD

**Issue by OneHatRepo** [WHMCS/developer-docs#156]
I am submitting the following to the API:
Array (
    [action] => GetPayMethods
    [username] => XXXXX
    [password] => XXXXX
    [clientid] => 490
    [responsetype] => json
)

The response I get is:
{"result":"error","message":"API Function Not Found"}

According to the docs, this method should be available.
https://developers.whmcs.com/api-reference/getpaymethods/

**Comment by OneHatRepo** [comment]
Got the same thing for AddPayMethod.

**Comment by mattpugh** [comment]
What version of WHMCS are you running? It will need to be 7.8.0 or later for these functions to be available.

**Comment by OneHatRepo** [comment]
Ah. I'm on Version: 7.7.1
Thanks for the info.
