### ISSUE TITLE
CCUpdate hook not work in WHMCS 7.8.3

### ISSUE THREAD

**Issue by rupeshNST** [WHMCS/developer-docs#158]
"CCUpdate" hook point is not working when credit card is added from adminarea and clientarea(account/paymentmethods/add)

I have fresh installation of **WHMCS 7.8.3**

**Comment by WHMCSMarcus** [comment]
Hello,

For an issue like this, please do submit a ticket to our technical support team for review: https://www.whmcs.com/support
