### ISSUE TITLE
[Feature] Escalation button within helpdesk

### ISSUE THREAD

**Issue by codieslab-tech** [WHMCS/developer-docs#168]
HelpDesk system will have "Escalate" button, for both customer and support agent.

1. Customer not happy with the service given, he can click "Escalate" and then special alert will be sent to selected managers.
2. Support agent unable to solve the issue and need escalate to seniors, he can click "Escalate" and choose to who which group of seniors this escalations should go. Escalation groups will be pre-created by the helpdesk manager.

**Comment by WHMCSMarcus** [comment]
Hello,

Please direct any feature requests to our Requests site: https://requests.whmcs.com/
