### ISSUE TITLE
Bug: Modern Order Template

### ISSUE THREAD

**Issue by bridgetsarah** [WHMCS/developer-docs#170]
Hello, I'm unable to create an account on your main website because I haven't purchased anything so I cannot submit a technical bug request. I have an issue with the 'Modern Template' in ordering and it looks brilliant when used, however their seems to be a loop in the programming, and refuses to take any product or add the product to basket to go to checkout. 

When I looked further into this, I went into the payment gateways module stripe and it advises that particular template is not updated to the specific requirements of stripe? Can you please look into this as would like to use this particular template for all services. I have had no issues with other templates apart from this one.

**Comment by WHMCSMarcus** [comment]
Hello,

I can confirm that the template in question is discontinued at this time: https://docs.whmcs.com/Discontinued_Order_Form_Templates

For any other support inquiries, please do submit via ticket at our website: https://www.whmcs.com/support
