### ISSUE TITLE
Missing Responsse JSON Get Ticket API

### ISSUE THREAD

**Issue by andp97** [WHMCS/developer-docs#171]
Missing example response JSON on GetTicket API

 https://github.com/WHMCS/developer-docs/blob/master/api-reference/getticket.md

https://developers.whmcs.com/api-reference/getticket/

**Comment by WHMCSPeter** [comment]
Thank you for your report. The JSON response example is not present. I'll be closing this issue out.

We appreciate you taking the time to let us know!
