### ISSUE TITLE
Minor typo in https://developers.whmcs.com/themes/customising/

### ISSUE THREAD

**Issue by jasonam** [WHMCS/developer-docs#176]
https://developers.whmcs.com/themes/customising/
Under Custom Logo:
"In order to set a custom logo it must either exist as /assests/img/logo.png or /assests/img/logo.jpg."
The assets directory name is incorrectly spelled...

**Comment by WHMCSMarcus** [comment]
Thank-you for your comments. We believe we have addressed this issue!
