### ISSUE TITLE
Error code for theme 6

### ISSUE THREAD

**Issue by Risimati20** [WHMCS/developer-docs#183]
The client area has a seamless functionality with the website, which is excellent but the website that it is linked with is an old website. We have updated it. May you please assist us with the following:
1. seamless functionality between the clientarea with new website (risimatihost.co.za). 
https://www.screencast.com/t/160xAkmcT4

2. May you please send the videos when doing customizations.

**Comment by WHMCSMarcus** [comment]
Hello,

In this case we would suggest looking into our Integration Service which we can provide the customizations you desire: https://www.whmcs.com/services/
