### ISSUE TITLE
Missing documentation for extra functionality of domain registrar

### ISSUE THREAD

**Issue by johnny-bit** [WHMCS/developer-docs#189]
In https://docs.whmcs.com/Domain_Renewal_Notices there's this blurb:

```
Where a registrar module supports it, WHMCS will also send a copy of the renewal notices to the registered name holder as defined in the WHOIS Record for a given domain.

Please Note: This functionality is only available in specific domain registrar module(s) at this time. They include:

    Enom

More will be added in due course. 
```

This is like that for at least 3 years now. Is there any info anywhere on how domain registrar can add different email to be notified (in case customer email is different from registrant mail)

**Comment by WHMCSMarcus** [comment]
Hello,

In this case please open a ticket with our support team [here](https://www.whmcs.com/support) who can further advise on this matter.
