### ISSUE TITLE
Mail Providers Initialisation Missing 

### ISSUE THREAD

**Issue by HardSoftCode** [WHMCS/developer-docs#200]
Here is the code 

```
use WHMCS\Module\MailSender\DescriptionTrait;

/**
 * Constructor
 */
public function __construct()
{
    $this->setDisplayName('Your Friendly Display Name');
}
```

**Comment by HardSoftCode** [comment]
Also you need to update the namespace from 

namespace Mail;
to
namespace WHMCS\Module\Mail;

**Comment by WHMCSPeter** [comment]
Thanks for your report. I have opened a case internally to have this reviewed by our Documentation team.

An update will be provided to the Documentation in due course.
