### ISSUE TITLE
getCurrency function unclear if this is userId or ClientId

### ISSUE THREAD

**Issue by Daniel-Manzau** [WHMCS/developer-docs#209]
https://github.com/WHMCS/developer-docs/blob/master/advanced/currency-formatting.md

post WHMCS 8.0 release getCurrency is unclear if this function is meant to take a ClientId or a UserId

**Comment by WHMCSMarcus** [comment]
Thank-you for this question. We have created a case for it to clarify this in our documentation.

This variable should be ClientId, not UserId
