### ISSUE TITLE
The closing PHP tag is not required in PHP files so could you remove these 3 new lines at the end of the code sample for us? Thanks!

### ISSUE THREAD

**Issue by Pkanjai** [WHMCS/developer-docs#225]
The closing PHP tag is not required in PHP files so could you remove these 3 new lines at the end of the code sample for us? Thanks!

_Originally posted by @mattpugh in https://github.com/WHMCS/developer-docs/pull/88#r201430375_

**Comment by WHMCSPeter** [comment]
This has been resolved in #234.

I will be closing this issue as it relates to a PR not currently in the Documentation.

Thank you for your assistance.
