### ISSUE TITLE
Dead Links

### ISSUE THREAD

**Issue by markhughes** [WHMCS/developer-docs#23]
Here are some dead links I've found:
* http://docs.whmcs.com/Hooks:AddonAdd
* http://docs.whmcs.com/Hooks:AdminAreaFooterOutput
* http://docs.whmcs.com/Hooks:LicensingAddonVerify
* etc..

See: https://www.google.com.au/search?q=whmcs+hooks

Perhaps setup some 301 redirects for these?

**Comment by MarkehMe** [comment]
Also http://docs.whmcs.com/classes/index.html should be redirecting to http://docs.whmcs.com/classes/7.1/index.html

**Comment by WHMCSMarcus** [comment]
Thank-you for your comments here. In the future we do recommend submitting a support ticket with these sort of requests via our Support Portal: https://www.whmcs.com/support

**Comment by markhughes** [comment]
> Thank-you for your comments here. In the future we do recommend submitting a support ticket with these sort of requests via our Support Portal: https://www.whmcs.com/support

@WHMCSMarcus you should update your README file then because the homepage of this repo says otherwise.

> We welcome you to create issues and submit pull requests for any suggestions, corrections and improvements you would like to see.
