### ISSUE TITLE
Documentation for AddOrder is missing the productids

### ISSUE THREAD

**Issue by bencromwell** [WHMCS/developer-docs#246]
https://developers.whmcs.com/api-reference/addorder/

The documentation does not reference the productids in the response, but they are returned.

It's either missing or was removed in a newer version of WHMS but it doesn't state its removal in the changelog.

The result I'm getting back from AddOrder contains these fields:
```
[orderid] => 76 
[productids] => 66 
[serviceids] => 66 
[addonids] => 
[domainids] => 
[invoiceid] => 70
```

**Comment by JRawly** [comment]
productids is a legacy field and has been replaced with serviceids.
Use serviceids in your own code.
productids will no longer be documented.

**Comment by bencromwell** [comment]
@JRawly Thanks for the reply. Are they always the same values and can be used interchangeably? Is it safe to do that?

**Comment by JRawly** [comment]
Hi, 
serviceids = productids always.
productids was removed as it may be confused with a product id which a service is assigned to.

**Comment by bencromwell** [comment]
That's great, thanks for clarifying!

**Comment by bencromwell** [comment]
@JRawly  Just a note on this, is it possible to get a changelog note added to show when it was deprecated?

**Comment by WHMCSPeter** [comment]
Hi @bencromwell,

I've opened an internal case (ID: CORE-16917) to have this reviewed and potentially have a changelog entry added to the API documentation for this.

Thanks for your input. It is appreciated.

**Comment by bencromwell** [comment]
Thanks @WHMCSPeter
