### ISSUE TITLE
Is there a 'noemail' boolean option on OpenTicket?

### ISSUE THREAD

**Issue by bencromwell** [WHMCS/developer-docs#247]
I found some reference to this here - https://whmcs.community/topic/213513-help-with-simple-openticket-internal-api/ - as well as in our codebase.

In several places we are calling OpenTicket via the `localApi` and passing a `'noemail' => true|false` option.

I couldn't find a reference to this property in the docs or on Wayback Machine: https://web.archive.org/web/20170108101921/http://developers.whmcs.com/api-reference/openticket/

Does this option exist?

**Comment by WHMCSMarcus** [comment]
Hello,

I can confirm that there is NOT a boolean called `noemail` available for this API endpoint. We definitely welcome suggestions for improvement however at our feature request site: https://requests.whmcs.com

**Comment by davidneimeyer** [comment]
To further elaborate, prior to WHMCS v7.8 the 'noemail' argument was an undocumented option.  If provided with a true value, in addition to preventing the general ticket open notification it could cause an array of undesirable outcomes (like no internal notifications) and thus was removed.
