### ISSUE TITLE
OpenTicket example password field

### ISSUE THREAD

**Issue by wesamly** [WHMCS/developer-docs#25]
Hello,
In the Example request in the [OpenTicket page](https://developers.whmcs.com/api-reference/openticket/), please change:
    `'password' => 'ADMIN_PASSWORD',`
to:
    `'password' => md5('ADMIN_PASSWORD'),`

thank you.

**Comment by mattpugh** [comment]
Hi @wesamly ,
Thank you for the suggestion. Our team is discussing internally making this change to all API code samples. Stay tuned.
Matt
