### ISSUE TITLE
Clarification on ClientArea output

### ISSUE THREAD

**Issue by cornzie** [WHMCS/developer-docs#250]
I have a scenario where I want to output a button on the product details page and addon when users are viewing the page with a specific product.

I have seen this for the provisioning module: https://developers.whmcs.com/provisioning-modules/client-area-output/

But there's nothing about this for addon modules. Is it possible to add a client area output on the product details page from an addon module? and if so, maybe you could consider adding this to the docs?

**Comment by WHMCSPeter** [comment]
Hello,

Please take a look at https://developers.whmcs.com/addon-modules/client-area-output/ for information on ClientArea Output for Addon Modules.

You can use hooks to add buttons to these pages in the navigations.

Please bare in mind that the Github issues board is for specific issues with the Developer Documentation and not a place for support requests.

For support with customisations, please use our forums at https://whmcs.community or in cases of a potential defect, please do reach out to our Technical Support team via https://www.whmcs.com/support.
