### ISSUE TITLE
Order Note

### ISSUE THREAD

**Issue by rick-ritts** [WHMCS/developer-docs#259]
Is there a way to add an note to an order using the AddOrder endpoint?

**Comment by WHMCSPeter** [comment]
Unfortunately, the functionality you're looking for here is not something that is currently offered by the AddOrder API within WHMCS.

However I can see how adding notes to orders via the AddOrder API method could be useful.  Therefore I would encourage you to please submit a request to our feature requests tracker where other users can contribute to and vote on your idea. Ideas with the most votes and activity do get reviewed by our team.

https://requests.whmcs.com

If you have any further questions, please don't hesitate to get back in touch via our official support methods: https://www.whmcs.com/support.

**Comment by rick-ritts** [comment]
Thanks for the quick reply. I tried to add this to the requests site but get a 500 Server Error when I login. Is that site down?

**Comment by WHMCSPeter** [comment]
Hi Rick,

Theres no known issue with the site. I was able to login with my credentials just fine. I couldn't find an account in our systems under your name here on GitHub. To avoid private information being shared publicly, could you please open a support ticket with us directly via the link provided above?

This will allow us to identify any specific issue with your account.

Thanks so much!
