### ISSUE TITLE
Hook AnnouncementAdd/AnnouncementEdit return empty string for title ?

### ISSUE THREAD

**Issue by wohahobg** [WHMCS/developer-docs#261]
Hello there,

We want to make Discord Announcement Notification whenever we post new Announcement in our whmcs. But when we do hook for that $vars['title'] is empty. And we can't get the title of the Announcement.

Can you please look at that and fix it in next update please?

Here is image from what does $vars return.

![whmcsNoTitle](https://user-images.githubusercontent.com/21145247/161422312-84cbe9f8-d293-4ba5-8dcc-4046e21e75a1.png)

Thanks

**Comment by WHMCSPeter** [comment]
Hello @wohahobg,

Thanks for reaching out! The Developer Documentation repo is for just that, only the documentation.

Could I please ask you to reach out via the Technical Support Team and in particular, directly via https://bugs.whmcs.com - This will allow our teams to review your bug report with your provided reproduction steps and open a bug case with our Development Team if required. An expected response to a bug report is between 24-72 hours.

Thanks for reaching out to us.

Peter
