### ISSUE TITLE
ResetPassword in role management in wrong place

### ISSUE THREAD

**Issue by SkitAndRogue** [WHMCS/developer-docs#263]
This is a small issue but can be confusing for users.

As per the API index ([https://developers.whmcs.com/api/api-index/](url)) the "resetPassword" function belongs to the User category and as such is called like that in the code. However, when adding API permission for this method in the role management tab on the admin page, resetPassword is located under the Client-tab instead of the User tab.

![image](https://user-images.githubusercontent.com/61006517/168035166-0e555fb5-d8fc-40e5-b382-d31e8fd677fc.png)
![image](https://user-images.githubusercontent.com/61006517/168035394-ced216d4-c64d-41a3-99a7-706c9323135b.png)

**Comment by davidneimeyer** [comment]
Hi @SkitAndRogue 
Many thanks for this report.  We will deliver this information to product development.  This repository is specifically for the developer documentation and in future we'd be happy to receive this sort of product feedback through Support; you can always share your findings in a [bug report](https://www.whmcs.com/members/bugreport.php). Cheers
