### ISSUE TITLE
dead link on footer qiuck start --> https://developers.whmcs.com/quick-start/

### ISSUE THREAD

**Issue by alqatari** [WHMCS/developer-docs#31]
in the footer
qiuck start --> https://developers.whmcs.com/quick-start/

**Comment by WHMCSChance** [comment]
@alqatari Thank you for bringing this to our attention.

I will look into this and get it updated!

**Comment by mattpugh** [comment]
This has also been reported in case #48. I am closing this and we will resolve it via the newer case.
