### ISSUE TITLE
Improve documentation for AddOrder

### ISSUE THREAD

**Issue by MarkehMe** [WHMCS/developer-docs#34]
The documentation for AddOrder does not describe how to add standard fields - only custom and optional fields.

Such as:
- server
- dedicated ip
- username
- password
- status

**Comment by mattpugh** [comment]
We do not support setting a server, dedicated IP, username, password or status at the time of placing an order. These are parameters that belong to a service and can only be set after a service has been created by an order using the [UpdateClientProduct](https://developers.whmcs.com/api-reference/updateclientproduct/) API method.

Matt
