### ISSUE TITLE
Confusing instructions in Creating Pages

### ISSUE THREAD

**Issue by TomasHurtz** [WHMCS/developer-docs#42]
https://developers.whmcs.com/advanced/creating-pages/

Instructions are fine until this line:

"Now when ready to test, upload the PHP file to the root WHMCS directory and the template file to your active template directory. Then visit the PHP file in your browser to try it."

But this is confusing - nowhere in the example does it mention the need for both the PHP and a template file.  I think what the instructions mean are; you need to create two files 1) a tpl page and 2) your custom php page - however, the article on really deals with creating one file (the example).  It also doesn;t really explain how the two files are linked.

The page could be written more clearly with better instructions for creating both files (php file and the tpl file).

Thanks

**Comment by WHMCSMarcus** [comment]
Thank-you for your comments. We believe the example now addresses these concerns
