### ISSUE TITLE
Is there a way to update configurable options through the API

### ISSUE THREAD

**Issue by BernardoSilva** [WHMCS/developer-docs#44]
Hi,

I would like to know if there is a way to update a product configurable option through the API?

I already looked into the [API](https://developers.whmcs.com/api/api-index/) Index but could only find API to create a product and nothing related to edit configurable options.

Thanks

**Comment by mattpugh** [comment]
You can modify the configurable options and their selected values for a given clients service via the [UpdateClientProduct](https://developers.whmcs.com/api-reference/updateclientproduct/) API command but if you are referring to adding or modifying configurable options at the product level, then that is not currently possible via the API.

Hope this helps!

Matt

**Comment by BernardoSilva** [comment]
I was looking to be able to do changes at product level.
Will be looking forward to see that feature available in future. :)

Thanks @mattpugh
