### ISSUE TITLE
Config Option Radio

### ISSUE THREAD

**Issue by ingobaab** [WHMCS/developer-docs#49]
The Default value of "radio" does not work as described in the [documentation](https://developers.whmcs.com/provisioning-modules/config-options/). The Example provided does also not work:
```
        "disk" => [
            "FriendlyName" => "Disk Space",
            "Type" => "radio", # Radio Selection of Options
            "Options" => "100MB,200MB,300MB",
            "Description" => "Radio Options Demo",
            "Default" => "200MB",
        ],
```

**Comment by WHMCSPeter** [comment]
Hello,

I believe this issue has since been resolved. If you are still experiencing issues, please do reach out to our Technical Support team who can provide further investigation if required.
