### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by HardSoftCode** [WHMCS/developer-docs#5]
https://developers.whmcs.com/hooks/sample-hook/

**Comment by mattpugh** [comment]
Thank you. The correct url for that page is https://developers.whmcs.com/hooks/sample/ We'll get the link updated.

**Comment by HardSoftCode** [comment]
Hi Matt 
Go to https://developers.whmcs.com/hooks/ and click on "Sample Hook" at the introduction list you get that error page
