### ISSUE TITLE
Unclear reference to "page 7"

### ISSUE THREAD

**Issue by aaron-suarez** [WHMCS/developer-docs#50]
I am doing some maintenance on an existing project that uses WHMCS Third Party Gateways. In trying to research my issue, I came across the page located [here](https://github.com/WHMCS/developer-docs/blob/17bc271d87bdd5dc35c35cda63dde84a50956a77/payment-gateways/third-party-gateway.md). It says "...refer to the Refund section on page 7 of the sample module."

From my Googling "WHMCS sample module", it appears there are a whole lot of sample modules, none of which seem to have pages. Could you please link the correct sample module and page to this confusing part of the text? I only started working with WHMCS two days ago and I'm not sure how all of it works, but this looks like something I should be able to click a link on to refer to.

Thank you very much!

**Comment by mattpugh** [comment]
Hey Aaron,
Thanks for letting us know about this. We've clarified that line and updated the link to point to a new page at https://developers.whmcs.com/payment-gateways/refunds/
Hope this helps!
