### ISSUE TITLE
Custom Functions for Provisioning Modules

### ISSUE THREAD

**Issue by ghost** [WHMCS/developer-docs#51]
I wroted a  Provisioning Module called license and it works well. But i am confused with Custom Functions.
For example, i wroted this:
```
function license_reset($vars){
    file_put_contents('/homw/wwwroot/leotome.org/a.txt','a');
    die();
}
```
and the TPL file is like this:
```
                    <form method="post" action="clientarea.php?action=productdetails">
                        <input type="hidden" name="id" value="{$serviceid}" />
                        <input type="hidden" name="modop" value="custom" />
                        <input type="hidden" name="a" value="reset" />
                        <input class="btn btn-warning btn-xs" type="submit" value="Reset License" />
                    </form>
```
But once i click that button, i only get the page refreshed.
How can i deal with that?

**Comment by mattpugh** [comment]
You need to ensure you have added the custom function 'reset' to the list of functions that a client is allowed to invoke. Please refer to the `_ClientAreaCustomButtonArray` function inside the Sample Provisioning Module for an example of how to do this:

https://github.com/WHMCS/sample-provisioning-module/blob/master/modules/servers/provisioningmodule/provisioningmodule.php#L443
