### ISSUE TITLE
Hooks index AfterRegistrarTransfer doubled up

### ISSUE THREAD

**Issue by johnrivelt** [WHMCS/developer-docs#55]
In Hooks index,
AfterRegistrarTransfer 
AfterRegistrarTransfer => this should be for (Executes after a successful domain transfer )
AfterRegistrarTransferFailed

**Comment by WHMCSPeter** [comment]
Thank you for your report and my apologies for the delay in responding. I can confirm that this has since been resolved and as  such, this case will be closed.

Thanks again!
