### ISSUE TITLE
Integration issues with Bluepay gateway

### ISSUE THREAD

**Issue by sagenext** [WHMCS/developer-docs#57]
Hi,

I have configured whmcs with bluepay and the payment is getting charged. There is only one issue that whmcs is unable to fetch customer's email address and phone number to send to the bluepay system. I talked to them several times and they told me that it's a whmcs issue. Please see what they told:
-----
We are not receiving the phone number or email address data within the transaction request on the BluePay gateway. Can you please verify which fields email address and phone number are mapped to within your whmcs software. The correct field names are below.
 
Email address = EMAIL
Phone number = PHONE
 
Tommy Miller
Integration Analyst
Direct: 630.300.2439
tmiller@bluepay.com
======================

Please help me in getting this fixed. Your help will be highly appreciated.

**Comment by WHMCSMarcus** [comment]
Hello,

For an issue like this please do submit a ticket to our technical support team via https://www.whmcs.com/support
