### ISSUE TITLE
Broken link in Developer docs

### ISSUE THREAD

**Issue by odeke** [WHMCS/developer-docs#64]
[http://developers.whmcs.com/payment-gateways/meta-data-params/](url)

The NEXT button at the bottom is pointing to a non-existent page.
It should point to
[http://developers.whmcs.com/payment-gateways/configuration/](url)

Cheers

**Comment by mattpugh** [comment]
Thanks for the heads up. We'll get this corrected.

**Comment by odeke** [comment]
Cheers
