### ISSUE TITLE
Third party page not found

### ISSUE THREAD

**Issue by Harpreetsinghbedi** [WHMCS/developer-docs#66]
Hello,

When i clicked on Third Party gateway link then i'm getting page not found "https://developers.whmcs.com/payment-gateways/third-party-gateways".

Please resolve it.

Thanks

Harpreet Singh

**Comment by mattpugh** [comment]
The correct url is https://developers.whmcs.com/payment-gateways/third-party-gateway/

What page are you seeing the incorrect link on?
