### ISSUE TITLE
The link is broken

### ISSUE THREAD

**Issue by blindlp** [WHMCS/developer-docs#72]
Broken link

**Comment by mattpugh** [comment]
Hi there,
Could you tell us which link you are referring to?
Thanks!

**Comment by GregKos** [comment]
Not sure if he means this one, but I stumbled upon this:

https://developers.whmcs.com/payment-gateways/meta-data-params/

Next button tries to take you to /provisioning-modules/configuration instead of /payment-gateways/configuration. I can create a pull request if you'd like.

**Comment by mattpugh** [comment]
Ok. If you can submit a PR that would be much appreciated. Thanks!

**Comment by GregKos** [comment]
The PR has been submitted since the 3rd! It has also been duplicated by #75

**Comment by mattpugh** [comment]
Thanks for submitting that. Your PR has now been accepted, merged and published to the site.
