### ISSUE TITLE
Error with documentation regarding SSO for provisioning modules

### ISSUE THREAD

**Issue by Vittfarne** [WHMCS/developer-docs#77]
https://developers.whmcs.com/provisioning-modules/single-sign-on/

has a link in the example code to:
http://docs.whmcs.com/Provisioning_Module_SDK_Parameters
which doesn't exist.

Also, the example code contains a syntax error,
```
$return = array(
		'success' = false,
	);
```

Should be either:
```
$return = array(
		'success' => false,
	);
```
or with PHP5.4+ [short array syntax](http://docs.php.net/manual/en/language.types.array.php):
```
$return = [
		'success' => false,
    ];
```

**Comment by mattpugh** [comment]
Thanks for bringing this to our attention. The url and sample code has now been updated.
