### ISSUE TITLE
Broken link in Developer docs 

### ISSUE THREAD

**Issue by ngstargate** [WHMCS/developer-docs#79]
On page https://developers.whmcs.com/advanced/currency-formatting/, on bottom link "See http://docs.whmcs.com/classes/7.0/WHMCS/View/Formatter/Price.html for more information." - wrong.

**Comment by mattpugh** [comment]
Thanks for letting us know.  The correct url for that is https://docs.whmcs.com/classes/7.1/WHMCS/View/Formatter/Price.html and we'll get it updated now.
