### ISSUE TITLE
Client->GetEmails API Error Result Type

### ISSUE THREAD

**Issue by MakdosBilisim** [WHMCS/developer-docs#80]
Hi, WHMCS APIs usually error result type is;

{
result: "error",
message: "Client Not Found",
}

But GetEmails API show error result like that;
{
**_status_**: "error",
message: "Client **_ID_** Not Found",
}

For your information.
Best Regards

**Comment by WHMCSMarcus** [comment]
Hello,

In this case we would request that you submit a ticket to our Technical Support team who can address this in further detail: https://www.whmcs.com/support
