### ISSUE TITLE
Example Request (CURL) returning unusable response

### ISSUE THREAD

**Issue by farzadkhaledi** [WHMCS/developer-docs#82]
Hello,

When I try to use : 
[https://developers.whmcs.com/api-reference/validatelogin/](url)

Response isn't unusable and json_decode function return false, I find out you need to put : 

`curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);`

to can curl return valid response and client can use.

**Comment by mattpugh** [comment]
Thanks for pointing this out. We'll get this fixed right now.
