### ISSUE TITLE
Where is User API?

### ISSUE THREAD

**Issue by 1057697328** [WHMCS/developer-docs#86]
I want to know where is User API...Not Admin...

**Comment by WHMCSPeter** [comment]
Hi @1057697328,

At this time, WHMCS provides a single API which requires an admin username/password or API credentials to authenticate with.

These APIs are driven with the admin in mind, not users however, we do welcome Feature Requests over at https://requests.whmcs.com where others can also vote on and comment on your request.

I hope this helps.
