### ISSUE TITLE
Custom API functions

### ISSUE THREAD

**Issue by IlyasDeckers** [WHMCS/developer-docs#9]
Hey,

I've been working with WHMCS for quite some time now. Great job btw.

For the project I am working on right now, I am using the API a lot. But it has some shortcomings for what I am doing right now. 

A quick sketch:

WHMCS will be used in this case as a pure client management system and provisioning system. All other tasks happen in a standalone laravel/angular web app.  Basically, we are creating a whole new front end and backend on a separate system. The reason why we are doing this is that we started developing our own public and internal API and most of our modules are accessible trough this API, this is where WHMCS was giving me a headache. To let everything work well with each other we need some extra API functions in WHMCS. After a lot of experimenting and reading outdated blog posts, I managed to write custom API functions in WHMCS. Maybe it isn't a bad idea to include this in the documentation.

A quick and dirty example how I created a new API function in WHMCS to return some information about the company:

```php
<?php
use Illuminate\Database\Capsule\Manager as Capsule;

  if (!defined("WHMCS")) die("This file cannot be accessed directly");

  function get_env($vars) {
    $array = array('action' => array(), 'params' => array());
    if(isset($vars['cmd'])) {
      //Local API mode
      $array['action'] = $vars['cmd'];
      $array['params'] = (object)$vars['pid'];
      $array['adminuser'] = $vars['adminuser'];
   
    } else {
      //Post CURL mode
      $array['action'] = $vars['_POST']['action'];
      unset($vars['_POST']['username']);
      unset($vars['_POST']['password']);
      unset($vars['_POST']['action']);
      $array['params'] = (object)$vars['_POST'];
    }
    return (object)$array;
  }
   
  try {
   // Get the arguments
    $vars = get_defined_vars();
    $postFields = getParam($vars);

    $data = Capsule::table('tblconfiguration')->get();

    $data = array(
      'companyname' => $data{1}->value,
      'email'       => $data{2}->value,
      'logo'        => $data{4}->value,
      'tos'         => $data{24}->value,
      'address'       => str_replace("\r\n","<br>", $data{40}->value),
    );

    $apiresults = array(“result” => “success”, data => $data);
  } catch (Exception $e) {
    $apiresults = array(“result” => “error”, “message” => $e->getMessage());
  }


?>
```

This works, but how can this be improved, what are some security measures that I have to include,... I would love to read more about creating custom API functions.

Keep up the good work,
Ilyas

**Comment by mattpugh** [comment]
Hi Ilyas,

While what you have here will work for now, we do not officially support creating your own API functions in this way and so can offer no guarantees this will always work in the future. That said, as far as security, WHMCS will handle the API authentication for you so you just need to ensure you're taking the appropriate security precautions with the actions and queries your code is performing. I would suggest looking at using the GetConfigurationValue API function for what you're doing above however: http://developers.whmcs.com/api-reference/getconfigurationvalue/

Regards,
Matt
