### ISSUE TITLE
CapturePayment for ACH gateways

### ISSUE THREAD

**Issue by JohnBurdell** [WHMCS/developer-docs#93]
Is there any way to implement the CapturePayment API to work with ACH payment gateways?  Maybe even as a separate API.

**Comment by WHMCSPeter** [comment]
Hello @JohnBurdell,

My apologies for a delay in response. If your ACH module is able to implement a `_capture` method, this API should be able to support usage of the CapturePayment API.

For further support, please reach out to our Technical Support Team, or at https://whmcs.community.
