### ISSUE TITLE
Get DomainGetNameservers response issue

### ISSUE THREAD

**Issue by izshreyansh** [WHMCS/developer-docs#99]
It is mentioned on [https://developers.whmcs.com/api-reference/domaingetnameservers/](url)
That possible error condition responses include:
- Domain ID Not Found
- Registrar Function Not Supported
- Registrar Error Message

I get **Registrar Error Message**, It would be nice to have little explanation for what this error message is for.

**Comment by shreyansh9226** [comment]
I found that this error occurs when there is an issue with Addon-Module.
In my case my primary server ip had to be linked with domain service provider.
